---
name: Chocolatey
on: push
jobs:
  choco-push:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v1
        env:
          APIKEY: ${{ secrets.APIKEY }}
        with:
          args: push whatpulse.3.1.nupkg -k="$APIKEY" --trace -s https://chocolatey.org/
